"""Change image to image_path #2

Revision ID: 489849e3707e
Revises: d5f0a8688ec3
Create Date: 2024-08-27 22:23:18.380688

"""
from typing import Sequence, Union

from fastapi_storages import FileSystemStorage
from fastapi_storages.integrations.sqlalchemy import ImageType
from alembic import op
import sqlalchemy as sa
from config import PROJECT_IMAGES_UPLOAD_DIR

# revision identifiers, used by Alembic.
revision: str = '489849e3707e'
down_revision: Union[str, None] = 'd5f0a8688ec3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
storage = FileSystemStorage(path=PROJECT_IMAGES_UPLOAD_DIR)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('image_path', ImageType(storage=storage), nullable=True))
    op.drop_column('project', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('project', 'image_path')
    # ### end Alembic commands ###
