"""Adding schema Order

Revision ID: d40d7951f9eb
Revises: 489849e3707e
Create Date: 2024-08-29 16:43:03.109048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from fastapi_storages import FileSystemStorage
from fastapi_storages.integrations.sqlalchemy import FileType

from config import ORDER_FILES_UPLOAD_DIR

# revision identifiers, used by Alembic.
revision: str = 'd40d7951f9eb'
down_revision: Union[str, None] = '489849e3707e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
storage = FileSystemStorage(path=ORDER_FILES_UPLOAD_DIR)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('project_type', sa.String(length=10), nullable=True),
                    sa.Column('budget', sa.String(length=50), nullable=True),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('tor_file', FileType(storage=storage), nullable=True),
                    sa.Column('customer_name', sa.String(length=50), nullable=True),
                    sa.Column('customer_number', sa.String(length=50), nullable=True),
                    sa.Column('customer_email', sa.String(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True),
                    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='user_pkey')
                    )
    op.drop_table('order')
    # ### end Alembic commands ###
