"""Change image_url to image field

Revision ID: d5f0a8688ec3
Revises: d3d3582a572b
Create Date: 2024-08-27 21:50:07.446236

"""
from typing import Sequence, Union

from fastapi_storages import FileSystemStorage
from fastapi_storages.integrations.sqlalchemy import ImageType
from alembic import op
import sqlalchemy as sa

from config import PROJECT_IMAGES_UPLOAD_DIR

# revision identifiers, used by Alembic.
revision: str = 'd5f0a8688ec3'
down_revision: Union[str, None] = 'd3d3582a572b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
storage = FileSystemStorage(path=PROJECT_IMAGES_UPLOAD_DIR)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('image', ImageType(storage=storage), nullable=True))
    op.drop_column('project', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('project', 'image')
    # ### end Alembic commands ###
