"""add feedback and user_services table

Revision ID: e665872bd5d5
Revises: f4cad2a32f0a
Create Date: 2024-08-24 21:00:50.855795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e665872bd5d5'
down_revision: Union[str, None] = 'f4cad2a32f0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
